### ISSUE TITLE
Would it be possible to import pad from image by selecting it via file browser

### ISSUE THREAD

**Issue by defenset** [jhaygood86/mauborgne#22]
Like it’s done on android, select image by going to it’s path, then load it, 
after that it’d would be automatically recognized and added to pads collection ?

**Comment by jhaygood86** [comment]
Very possible. That's a good feature request. I'll look into it!

**Comment by defenset** [comment]
great, good to hear that!

**Comment by jhaygood86** [comment]
This will be in 0.7.0

I have submitted the update to the elementary appcenter and to flathub. It's already available in my custom remote.

**Comment by defenset** [comment]
I updated it from flathub but for some reason I’m not able to upload qr code from image, did you try to do it via flatpak version ? Is it working for you?

**Comment by jhaygood86** [comment]
It is working for me.

Do you have the image you are trying to do? I can see if I can reproduce
the problem.

Also, what distro are you using?

**Comment by defenset** [comment]
Ubuntu MATE, 5.13.0-21

I run it in terminal via ‘flatpak run io.github.jhaygood86.mauborgne’, and it says that:
Gtk-Message: Failed to load module "appmenu-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"

Even though it looks like is installed, at least those below were, did quick reinstall just in case:
‘sudo apt --reinstall install libcanberra-gtk-module appmenu-gtk-module-common’

but it didn’t change much.

those below also are installed:

appmenu-gtk-module-common
appmenu-gtk2-module
appmenu-gtk3-module
appmenu-registrar

libcanberra-gtk-module
libcanberra-gtk0
libcanberra-gtk3-0
libcanberra-gtk3-module
libcanberra-pulse
libcanberra0

Flatpak version 1.10.2

Any suggestions what packages are missing?

See also output file attached, I get it when I try to load exported files from aegis

[output.log](https://github.com/jhaygood86/mauborgne/files/7534687/output.log)

**Comment by jhaygood86** [comment]
Do you have xdg-desktop-portal-gtk installed as well as a freedesktop
portal compatible secrets manager?

**Comment by defenset** [comment]
I have those below installed

xdg-desktop-portal
xdg-desktop-portal-gtk-dev
xdg-desktop-portal-gtk

libsecret-1-0
libsecret-1-dev
libsecret-commom
libsecret-tools

gnome-keyring
gnome-keyring.pkcs11
libpam-gnome-keyring
python3-keyring

I found this, that says it's distro problem:

https://gitlab.gnome.org/GNOME/geary/-/issues/817

and this info

https://opensource.com/article/19/11/secrets-management-flatpak-applications

**Comment by jhaygood86** [comment]
The "failed to load modules", I wouldn't worry about it, that's a red herring.

The real issue is that the flatpak secrets portal isn't responding. That is entirely up to the platform (MATE) to get working. Until MATE fixes it, there's nothing I can do from my side. It works fine in supported versions of GNOME and Pantheon.
