### ISSUE TITLE
[Flatpak] This app is using obsolete runtime. Please update to newer platform

### ISSUE THREAD

**Issue by RDKRACZ** [jhaygood86/mauborgne#28]
The GNOME 41 runtime is no longer supported as of September 17, 2022. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   io.github.jhaygood86.mauborgne

**Comment by jhaygood86** [comment]
This is now fixed in elementary appcenter. I will update flathub shortly.

**Comment by jhaygood86** [comment]
This is now fixed in flathub as well
