### ISSUE TITLE
Feature Request: Importing and Exporting

### ISSUE THREAD

**Issue by BrandonEugeneWalker** [jhaygood86/mauborgne#3]
It would be nice (if possible) to be able to import and export accounts for easy transfer between systems.

**Comment by jhaygood86** [comment]
I added the ability to export an account via a QR Code (so you can import into other apps as well) in 0.1.0 (submitted to appcenter just now). Since we already can import using a QR Code, will that solve the ask?

**Comment by BrandonEugeneWalker** [comment]
Cool, I think that does.
